// Hand-maintained index of the site's actual content, chunked by section,
// used for lexical + synonym retrieval before answering a chatbot question.
// Keep this in sync with the HTML pages when their content changes —
// there's no build-time scraper, this is the source of truth for search.
const CONTENT_INDEX = [
  // ---- Home ----
  { page: "Home", url: "index.html", heading: "About Us", text: "Wolf Club is a semi-realistic wolf based art and roleplay group with a little more emphasis on the realistic side, similar to Balto, Spirit, or The Lion King. Characters can speak, have emotions and facial expressions, but should still mostly act, look, and move like real wolves. Welcomes writers and artists of every skill level." },
  { page: "Home", url: "index.html", heading: "News", text: "The News panel links to the current month's update journal (MSE + prompts) and Helpful Links: Bones Currency, Bones Shop, Activity Check, Character Creation, Familiar Creation, Packs of the Club, Member Handbook." },
  { page: "Home", url: "index.html", heading: "Character of the Season", text: "Each season the front page features a Character of the Season with a portrait, blurb, an Autumn Winner badge, and a Previous Winners link." },
  { page: "Home", url: "index.html", heading: "Featured Gallery", text: "A rotating gallery of featured member artwork on the front page." },

  // ---- Joining ----
  { page: "Joining", url: "joining.html", heading: "Joining Wolf Club overview", text: "Wolf Club is a closed group with a member cap of 75. Openings are announced by admin discretion and mentioned in advance in journals. Minimum age to join is 18, due to mature themes in stories and RP." },
  { page: "Joining", url: "joining.html", heading: "While waiting for an opening", text: "Read the rules and bones info, be mature (past behavior toward staff/members is considered), read about the packs' cultures before applying, don't harass members or staff about openings, and keep practicing your art/writing — staff like to see an active gallery." },
  { page: "Joining", url: "joining.html", heading: "Applying tips", text: "Follow the Character Creation instructions exactly. Personality needs 200 words minimum, history 300 words minimum — more is recommended. Give characters both positive and negative traits (avoid Mary-Sues). Don't rely purely on disabilities/injuries or traumatic backstories to make a character interesting. Artistic skill and popularity/watcher count do NOT affect whether you're accepted." },
  { page: "Joining", url: "joining.html", heading: "Returning applicants", text: "If removed for inactivity or left without exit pieces, you start over completely (fees, cooldowns, bones). If you left with exit pieces, returning characters keep their bones but first-character rules (no mutations, etc.) apply again. A bonded mateship can remain active on rejoin if the mate or both wolves properly exited. No inactivity fee applies to returning members who provided exit pieces." },
  { page: "Joining", url: "joining.html", heading: "After being accepted", text: "Be active (join plots, RP, reach out to others), look around the Discord server, keep reading the pack and group rules, and check the staff-made Crash Course doc for a quick overview if the handbook feels overwhelming." },

  // ---- Staff ----
  { page: "Staff & Leadership", url: "staff.html", heading: "The Council", text: "The Council (Zoketi, jackalloops, Lachtaube) upholds the staff Code of Conduct, gives final verdicts when staff can't agree, and assists moderators with group logistics." },
  { page: "Staff & Leadership", url: "staff.html", heading: "Moderators", text: "Moderators (unknowntalent, Willowbyrd, itsloach, SpacemanNik, RohannRoh) run day-to-day member content and logistics, from plot events to general maintenance." },
  { page: "Staff & Leadership", url: "staff.html", heading: "Pack Leaders", text: "Pack Leaders run their pack's prompts/plots and represent their pack on staff matters. Current Pack Leaders: Heart Nadia of Chandor (Zoketi), Jarl Virago of Fellfang (IraWolfxn), Maelys of Telcoyu (littleredloup), Lady Keezheekoni of Riverfell (IndiDreamer), Cyrus Ramman of Xassa (MISTY), Radiance Inkeri of Allruh (ThorinFrostclaw), Honorable Bentwood of Grayard (Lachtaube), Prime Beatrice of Virtus (SilverPocky)." },
  { page: "Staff & Leadership", url: "staff.html", heading: "Scribes", text: "Scribes create content for their pack and help evaluate new characters. Current Scribes: Scribe of Fellfang (Willowbyrd), Scribe of Riverfell (EternalHusky), Scribe of Virtus (BeastyBby), Scribe of Allruh (hobbyjozzler), Scribe of Xassa (Cipsis-Sketch), Scribe of Telcoyu (Heldoryn)." },
  { page: "Staff & Leadership", url: "staff.html", heading: "Staff Code of Conduct", text: "Staff must be professional, respectful, kind, communicate clearly, listen to differing opinions, stay humble, apply rules equally to everyone including friends, stay active (roughly 1 hour/day or combined weekly hours depending on role), take breaks when needed instead of ghosting, escalate concerns, keep member disputes confidential, hand off responsibilities cleanly when leaving a role, and never use a staff departure to vent or take jabs at the departed member." },
  { page: "Staff & Leadership", url: "staff.html", heading: "Staff Strike System", text: "A 3-strike plan tracks staff behavior concerns; strikes are issued privately (never via bot), tracked by Mods/Council with receipts, and fall off after 3 months. Possible added consequences: temporary ban from IC events or Discord channels, loss/forfeiture of a month's bones, or other Mod/Council-approved discouragements." },

  // ---- Group Rules ----
  { page: "Group Rules", url: "group-rules.html", heading: "Member Code of Conduct", text: "Core value: Be Safe & Have Fun. Be respectful and polite — bigotry/hate speech, gossiping/demeaning other members' work, and public blacklisting/callouts are never tolerated. Be mature — keep IC/OOC feelings separate, respect RP partners' boundaries, don't pressure people into RP, be upfront about intentions, and anyone can withdraw from a collab/plot at any time. Be kind, especially toward volunteer staff who may need time to respond." },
  { page: "Group Rules", url: "group-rules.html", heading: "General Group Rules", text: "Members must follow dA's Terms of Service. Note the WCAdmin account (or Mod Ticket) for questions rather than personal staff accounts. Plot questions go via Note/Ticket. Sensitive issues (staff complaints, disputes) can go privately to a Council member instead. Art theft and godmodding are not permitted, but joining WC means consenting to your character appearing in others' art/memes/backgrounds. Discord access isn't mandatory after a member's first three months." },
  { page: "Group Rules", url: "group-rules.html", heading: "Member Strike System", text: "Wolf Club generally follows a 3-strike system: three reminders, then three warnings, before suspension or a permanent ban — though staff can escalate faster if community safety requires it. Suspension can include removal from Discord channels, in-character restrictions, partial bone forfeiture, or a permanent ban." },
  { page: "Group Rules", url: "group-rules.html", heading: "Group Submission Guidelines", text: "All art must be your own (except some application-art exceptions). No premade templates, linearts, AI-generated art, NFTs, or AI writing tools for bone-worthy content. Commissioned/gifted/collaborated art needs credit and proof of usage rights. Content should go in the right faction folder. Non-members can't submit but current members may post fan-art/gifts with permission." },
  { page: "Group Rules", url: "group-rules.html", heading: "Mature Content Guidelines", text: "WC is a mature RP group but does not allow explicit 'R' rated depictions. Sensitive/triggering content needs CW/TW in the description and title. Titles must stay free of uncensored profanity even though RP/art bodies can be marked mature." },
  { page: "Group Rules", url: "group-rules.html", heading: "Discord Rules", text: "Discord is for current members only — don't share invite links externally. No gossip/defamation, keep personal/political topics to DMs, avoid excessive venting, use spoiler tags with a TW label for sensitive topics, no mini-modding, and route serious questions to WCAdmin/Mod Tickets rather than the Q&A channel. Breaking these rules can mean removal from Discord and/or the group." },

  // ---- Member Guides landing ----
  { page: "Member Guides", url: "member-guides.html", heading: "Getting Started", text: "New members set up a profile, explore the community/gallery, and visit the Packs page to find a group matching their interests." },
  { page: "Member Guides", url: "member-guides.html", heading: "Community Rules summary", text: "Be respectful, no plagiarism (always credit artists), keep content PG-13, no spam/advertising, and report concerns to a moderator immediately." },
  { page: "Member Guides", url: "member-guides.html", heading: "Roleplay Tips", text: "Develop detailed characters with backstory and quirks, collaborate rather than controlling others' characters or forcing outcomes, write with proper grammar and enough detail, and always discuss and respect RP partners' comfort levels and boundaries." },

  // ---- Bones ----
  { page: "Bones Currency System", url: "bones.html", heading: "What are Bones", text: "Bones are Wolf Club's in-game currency/point system. They are character-specific (don't pool between characters, except for buying new characters or familiars). Nothing posted before a character is accepted counts. Only your own art/lit earns bones — gifts/commissions from others don't, but canon collabs and RP with another active member's characters do." },
  { page: "Bones Currency System", url: "bones.html", heading: "Automatic Bones", text: "Characters automatically get 2 bones when they join the group. Voting in the seasonal Character of the Season poll is worth 1 bone to a character of your choosing." },
  { page: "Bones Currency System", url: "bones.html", heading: "Illustration bone values", text: "A full-body illustration (50%+ of the wolf visible, colored, with a real background) = 2 bones. A half-body illustration = 1 bone. Bonuses available: +1 Familiar bonus, +1 Clubian bonus (featuring another member's character), +1 Plot bonus." },
  { page: "Bones Currency System", url: "bones.html", heading: "Comic pages", text: "Comics need 2+ panels, each panel valued like its own illustration (half-body panel = 1 bone, full-body panel = 2 bones); doesn't stack for multiple characters in one panel. Clubian bonus applies per new non-owned character across the whole page." },
  { page: "Bones Currency System", url: "bones.html", heading: "Roleplay and literature bone values", text: "Paragraph-style RP = 1 bone per 3 posts per character (+1 bone per additional 3 posts). Literature-style RP (2 characters) = 1 bone per 1000 words per participant, +500 words per extra character. Solo literature = 1 bone per 500 words." },
  { page: "Bones Currency System", url: "bones.html", heading: "Animation and PMV bone values", text: "Simple animation (blink, ear twitch) = 1 bone. Moderate animation = 4 bones. Complex animation (run cycles, voice overs) = 8+ bones. PMVs = 8+ bones for one minute, +1 bone per additional 30 seconds; PMVs are non-negotiable pricing." },
  { page: "Bones Currency System", url: "bones.html", heading: "Monthly Special Events (MSE)", text: "MSE memes are worth 2-3 bones: +1 bone bonus during their featured month, +1 more if the meme has 4+ distinct panels." },
  { page: "Bones Currency System", url: "bones.html", heading: "What is NOT eligible for bones", text: "Heart charts, relationship trackers, medallions, most OOC/non-canon art, gifts/commissions (except official Secret Santa), and chibis/pixels/icons/stamps do not earn bones unless tied to a listed prompt or MSE." },
  { page: "Bones Currency System", url: "bones.html", heading: "Cashing bones", text: "To record bones, Note WCAdmin or submit a Bone Cashing Ticket on Discord with a link to the piece, the number of bones claimed, any bonuses claimed, and your previous/new bone totals. Pieces must be cashed within 2 months of their submission date, and bones count toward the month they're cashed, not posted." },

  // ---- Activity Check ----
  { page: "Activity Check", url: "activity-check.html", heading: "Monthly member activity", text: "All members must earn at least one bone per month by cashing bones. Missing a month gives a red dot; a second lapse within the next three months gets the member removed for inactivity. Activity Forgiveness can be requested via Note/Mod Ticket at least a week before turnover for things like illness, travel, or finals." },
  { page: "Activity Check", url: "activity-check.html", heading: "Seasonal character activity", text: "Every character needs at least one canon piece of content each season (3 months); MSEs/memes don't count. Characters that miss a season are force-retired, losing all bones, rank, and accessories. Bringing a force-retired character back costs a +3 bone fee on top of the normal character slot cost, and it restarts at the lowest rank with 0 bones." },
  { page: "Activity Check", url: "activity-check.html", heading: "Character retirement and death", text: "Retiring a character requires an Exit piece (art, RP, or story showing them leaving). Retired characters (not deceased) can rejoin later for the standard character fee and keep their prior bone total. Characters marked 'deceased' can never be revived — mark them 'retired' instead if you might want them back." },

  // ---- Character Creation ----
  { page: "Character Creation", url: "character-creation.html", heading: "General character rules", text: "Only wolves and approved Other Creatures may be characters — no wolf-hybrids. Characters can't be fan-based copies of movie/show wolves (no Balto, Ghost, Bolt clones), can't have real magical powers (only believe they might), and dreams are never literal visions. Ties to disbanded packs need explicit approval." },
  { page: "Character Creation", url: "character-creation.html", heading: "First and other characters", text: "New members' first character must be a pack-wolf, at least juvenile age, with no mutations. After 3 months you can add more characters (1-month cooldown between each after that). Members can have up to 10 characters; the first two are free, later ones cost bones. Max 3 characters per pack. Loner/Other Creature count can't exceed your pack-character count, capped at 3 total." },
  { page: "Character Creation", url: "character-creation.html", heading: "Other Creatures / other species", text: "Approved non-wolf species include coyotes, bears, bobcats/lynxes/mountain lions, foxes, mustelids, opossums/porcupines/raccoons, and birds of prey. Other species can't be herbivorous grazers, can't crossbreed with wolves, can't join a pack (though territory may overlap), and familiars for them must be 25% smaller than usual." },
  { page: "Character Creation", url: "character-creation.html", heading: "Biography required fields", text: "Applications need Name, Age (Pup 0-3mo, Juvenile 3-9mo, Young Adult 9mo-2/3yr, Adult 4-8yr, Aged Adult 9-11yr, Elder 12yr+), Gender/pronouns, Height, Weight, Build, Territory, Family, Rank (new members start as Omega with no task), Personality (200 words min), Pre-Group History (300 words min), Group History, and Other." },
  { page: "Character Creation", url: "character-creation.html", heading: "Height and weight guidelines", text: "Males run 32-36 inches, females 30-34 inches (extremes 28-36 with mutation for anything past). Weight range is roughly 60-120 lbs (as low as 50, as high as 130 with a reason). Height-to-weight pairs roughly: 30in=60lbs up to 36in=120lbs." },
  { page: "Character Creation", url: "character-creation.html", heading: "Design guide — markings", text: "Coats range from near-white through blond/cream/tan/reddish/ochre to gray/silver/brown/black, not overly saturated. Ticking and flecking (small color variations) are allowed if uniform and non-spotty. Border markings must be wide enough not to read as thin outline stripes. Sock/leg markings must be symmetrical, non-high-contrast, and plausible for a wolf. Intricate/unnatural markings (stripes, swirls, symbols, dog-like patches, piebald/merle coloring) are not permitted." },
  { page: "Character Creation", url: "character-creation.html", heading: "Design guide — fur, eyes, scars", text: "No large/extreme hairdos or hair covering the eyes; moderate leg feathering is fine. Eyes can be yellow/gold/amber/brown/green/hazel/blue/gray, bi-colored allowed, pupils normally black. Noses/paw-pads must be darker than the coat (unless albino). Scarring can't include severe head/jaw injuries, multiple missing/broken limbs, severe burns, embedded objects, or exposed skeleton." },

  // ---- Pack Creation ----
  { page: "Pack Creation", url: "pack-creation.html", heading: "Pack Creation overview", text: "Pack applications are currently CLOSED. Becoming an alpha no longer auto-grants an admin/staff role — Pack Leader is its own staff position, optionally paired with a second role. Alphas should expect to devote significant weekly time, earn at least 1 bone/month, and commit to running the pack for at least a year." },
  { page: "Pack Creation", url: "pack-creation.html", heading: "Drafting a pack", text: "Pack concepts must be original (inspired by, not copied from, other cultures/media) and shouldn't overlap too heavily with existing packs. The pack's main page should cover: pack & members, pack & outsiders, culture, rules/laws, up to 6 tasks, and hierarchy (a version of Omega/Delta/Gamma/Theta/Beta/Alpha is required, extra plot ranks allowed)." },
  { page: "Pack Creation", url: "pack-creation.html", heading: "Pack tryout process", text: "New pack concepts can only be submitted during an official opening window via Google Form; late submissions aren't considered. Staff review and shortlist applicants, then the community votes via Google Form; the highest-voted pack(s) get implemented." },
  { page: "Pack Creation", url: "pack-creation.html", heading: "Two alphas and pack costs", text: "Packs with two alphas both pay the 30-bone fee (only one submits the tryout form; both get the Pack Leader rank). A brand-new alpha character needs an available character slot and bones. New packs cost 30 bones on top of any new-character costs." },

  // ---- Mates and Pups ----
  { page: "Mates and Pups", url: "mates-and-pups.html", heading: "Mates overview", text: "Characters can't officially become mates or have pups without both cashing the required bones fees. There are two mate types: a permanent bonded mate (marriage-style, may or may not have pups) and a temporary mate (a fling resulting in pups)." },
  { page: "Mates and Pups", url: "mates-and-pups.html", heading: "Bonded mate requirements", text: "Bonded mates need 3 pieces developing the relationship, must have expressed feelings for at least 1 season (3 months), and must wait 1 real-life month as official mates before cashing a pregnancy. Polyamorous relationships split pregnancy/litter costs evenly." },
  { page: "Mates and Pups", url: "mates-and-pups.html", heading: "Temporary mate requirements", text: "A temporary mate (fling) only needs 1 piece showing the pair agreeing to a litter or otherwise indicating the fling." },
  { page: "Mates and Pups", url: "mates-and-pups.html", heading: "Litters and pups rules", text: "Pregnancy fees must be paid before pups go up for free-form adoption; pregnancies last six IRL weeks. Playing a pup from your own litter waives the New Character fee once per litter. No more than 10 pups can be up for adoption at once. Pup names can be reserved at pregnancy-cashing time if paid for immediately." },
  { page: "Mates and Pups", url: "mates-and-pups.html", heading: "Guardians and bringing in pups", text: "Pups need either 2 NPC parents or 2 player-character parents who went through the pregnancy process (never 1 NPC + 1 PC, except adult characters conceived before joining). Pups brought into the Domain must have a Guardian and be at least weaning age (2 months) unless the guardian is nursing. Guardians can care for up to 4 pups and must pay the Guardian Fee (10 bones for a pack pup, 15 for a loner pup)." },

  // ---- Shop ----
  { page: "Wolf Club Shop", url: "shop.html", heading: "Accessory prices", text: "Accessory bundles cost bones: Flowers, Leaves, Twigs, Small Bones, Feathers, Insect Parts, and Shed Snake Skin = 4 bones. Small Pelt = 6 bones. Large Pelt and Large Skull = 9 bones. Pet Rock = 3 bones. Accessories/species must be native to North America (loose exceptions for non-native plants) and must be approved for familiars too." },
  { page: "Wolf Club Shop", url: "shop.html", heading: "Familiar price", text: "A Familiar (bat, bird, reptile, small rodent/mustelid, up to opossum-sized) costs 30 bones. Can be paid for with another of your own characters' bones and can be transferred free between your own characters." },
  { page: "Wolf Club Shop", url: "shop.html", heading: "Rank and task prices", text: "Delta rank = 5 bones (1 canon piece). Gamma = 10 bones (3 canon pieces). Theta = 20 bones (5 canon pieces). Changing task = 5 bones and resets you to Delta rank." },
  { page: "Wolf Club Shop", url: "shop.html", heading: "Faction change prices", text: "Loner to Pack = 1 bone. Pack Switch = 10 bones. Leaving a Pack to Loners = 15 bones. A Loner Band costs 15 bones startup + 10 bones annually." },
  { page: "Wolf Club Shop", url: "shop.html", heading: "Mutation prices", text: "Minor Limb Loss = 10 bones. Major Limb Loss = 25 bones. Minor Mutation (small cosmetic changes) = 8 bones. Major Mutation (gigantism, dwarfism, chimera, albinism) = 20 bones." },
  { page: "Wolf Club Shop", url: "shop.html", heading: "Mate bone costs", text: "Bonded mates: 6 bones each same-pack, 10 different packs, 13 loners, 8 loner+pack, 6 other creatures. Temporary mates: 7/12/14/9/7 bones respectively for the same categories." },
  { page: "Wolf Club Shop", url: "shop.html", heading: "Pregnancy bone costs", text: "Bonded mate pregnancy: 6 bones each same-pack litter, 9 different packs, 8 loner, 9 loner x pack, 6 other creature. Temporary mate pregnancy: 10/15/15/12/10 bones respectively." },
  { page: "Wolf Club Shop", url: "shop.html", heading: "Pup and litter bone costs", text: "Pups cost the same whether bonded or temporary mates: 6 bones for 1 pup, 12 for 2, 24 for 3, 48 for 4, or 18 bones for a random D4 dice roll (2-4 pups). Guardian fees: 10 bones for a pack pup, 15 for a loner pup. Max litter size: 4 for pack, 3 for loner, 1-4 for other creatures." },
  { page: "Wolf Club Shop", url: "shop.html", heading: "New character prices", text: "1st and 2nd characters are free. 3rd = 12 bones, 4th = 22, 5th = 24, 6th = 26, 7th = 34, 8th = 42, 9th = 54, 10th = 66 bones. Bringing back a character force-retired for inactivity costs an extra 3-bone Inactivity Fee." },
  { page: "Wolf Club Shop", url: "shop.html", heading: "New pack price", text: "Creating a new pack (after it wins the community vote) costs 30 bones." },
  { page: "Wolf Club Shop", url: "shop.html", heading: "Making a purchase", text: "All shop purchases are submitted the same way as bone cashing: Note WCAdmin or submit a Bone Cashing Ticket on Discord, stating what you're buying, its bone cost, and your before/after bone totals. Approval-needed purchases (mutations, accessories, familiars, faction changes) should include a reference of what you want approved." },

  // ---- Packs ----
  { page: "Packs", url: "packs.html", heading: "Active packs overview", text: "Wolf Club's active packs: Chandor (sanctuary, peaceful, naturalistic, protective), Fellfang (code of honor, witchdoctors, mysterious), Telcoyu (devout, occultism, hired killers, devious), Riverfell (matriarchy, sellswords, traders, other creatures welcome), Xassa (pursuits, records), Allruh (Dark Academia, Paranoid, Astronomy, Ancestral), Grayard (esoteric, militaristic, doomsday, integrity, humility), Virtus (militant, strength, fortitude, pride)." },
  { page: "Packs", url: "packs.html", heading: "Loners and loner bands", text: "Loners live independently outside pack structure and are welcome in most territories if they respect pack laws. Loner Bands are transient traveling groups — e.g. The Scourgers, a notorious band that travels together for survival and strength in numbers." },
  { page: "Packs", url: "packs.html", heading: "Other Creatures in the Domain", text: "Non-wolf species roam the Domain too; some packs like Riverfell welcome other species into their ranks." },
  { page: "Packs", url: "packs.html", heading: "Disbanded packs", text: "Former packs that no longer exist: Kausen (dispersed into Chandor when alpha Gregor aged), Morrow (wiped out by disease), Vale (led out by alpha Loki after hard times), Dawnguard (merged with Heyl, then collapsed after alpha Nahi's death), Damasca (nomadic pack that moved on during a drought), Blutwald (a violent dictatorship defeated in war by Aryn), Havir (an isolated religious pack ended by a meteor strike), and Aryn (rebuilt more than once, eventually disbanded after a hurricane displaced its members)." },

  // ---- Chandor (full pack page) ----
  { page: "Chandor", url: "chandor.html", heading: "Chandor overview", text: "Chandor (\"SHAWN-dor\") is a small, familial sanctuary pack founded by Aethelynda for wolves with nowhere else to go. Tags: sanctuary, peaceful, naturalistic, protective. Status is earned by experience and trust rather than title; the pack is humble, light-hearted, and welcomes wolves of every background." },
  { page: "Chandor", url: "chandor.html", heading: "Chandor culture and religion", text: "Chandor has no set religion — members may believe what they wish as long as it harms no one; the Northern Lights are believed to be where dead wolves' spirits rest. No restrictions on mates or courtship. Territory is a lush temperate woodland valley with rivers, a lake, and a densite north of the main river." },
  { page: "Chandor", url: "chandor.html", heading: "Chandor foreign relations", text: "Chandor is open and accepting to nearly everyone: allied with Riverfell and Xassa, wary of Fellfang, unknown relations with Telcoyu, Allruh, Grayard, and Virtus." },
  { page: "Chandor", url: "chandor.html", heading: "Chandor pack life and festivals", text: "Chandor holds Springfest, Summerfest, Autumnfest, and Winterfest at the start of each season, plus Remembrance (an evening honoring the dead and welcoming new lives) and Storydances performed by the Owlwatch. Punishments range from a verbal scolding up to public trial and exile for wolfslaughter." },
  { page: "Chandor", url: "chandor.html", heading: "Chandor tasks and ranks", text: "Chandor's tasks are Bearguard (warriors/guardians), Owlwatch (historians, storytellers, pup-watchers), Lynxscout (hunters and scouts), and Elkward (healers). Ranks top-down: Heart (alpha), Roots/Councilors, Branches (thetas), Bark (gammas), Saplings (deltas), Leaves (omega), Juveniles, Seedlings (pups), Winterlights (deceased)." },

  // ---- Fellfang (full pack page) ----
  { page: "Fellfang", url: "fellfang.html", heading: "Fellfang overview and history", text: "Fellfang (Code of Honor, Witchdoctors, Mysterious) were once nomadic traders known as the First Ways, fell into a violent marauding era under Arn and later Jarl Story, were redeemed by Jarl Fable, then rebuilt under Jarl Lincoln's Golden Era before the Hive Wars killed him. His successor Jarl Valera's cruel reign ended when she vanished; the pack currently follows the newly appointed Jarl Virago, a former Chandorian." },
  { page: "Fellfang", url: "fellfang.html", heading: "Fellfang beliefs and healing", text: "Fellfang believes in universal balance, ghosts/draugr, and spirits (Koma, Valda the trickster, Eir). Witch-Doctors are Fellfang's renowned healers, blending herbalism with spirituality. Marauding is now strictly forbidden; their Code of Honor revolves around balance, justice, and chivalry." },
  { page: "Fellfang", url: "fellfang.html", heading: "Fellfang tasks and ranks", text: "Tasks: Sage (history/omens), Witch-Doctor (healers), The Hunt (providers/population control), Vanguard (guards/diplomatic scouts). Ranks top-down: Jarl (alpha), Aldinwitch and Skalsang (special ranks), Thane (beta), Brandr (theta), Drengr (gamma), Skuldcarl (delta), Serf (omega), Kind/Kinder (pups)." },
  { page: "Fellfang", url: "fellfang.html", heading: "Fellfang laws", text: "Fellfang's Code of Honour covers fair fighting, honesty, non-lethal duels for disagreements, and obedience to the Jarl. Other laws: mate approval needed from the Jarl, marriage is monogamous, outings can't exceed 2 days without approval, and crimes are punished by scarification, exile, or death." },

  // ---- Allruh (full pack page) ----
  { page: "Allruh", url: "allruh.html", heading: "Allruh overview and history", text: "Allruh (Dark Academia, Paranoid, Astronomy, Ancestral) descends from Aeon, the first wolf, who escaped astral beings called the Creators/Them and became the ancestor of the Aeonkin. The pack lives nocturnally underground in mountain tunnels, paranoid that the Creators will return through the moon gateway." },
  { page: "Allruh", url: "allruh.html", heading: "Allruh laws and beliefs", text: "Core laws: remember Aeon, prevent Them from gaining influence over any wolf (no bird familiars/friends, watch the moon), do not cause harm, do not dream (unexplained dreams must be reported to an Apothecary or Scholar). The Radiance (alpha) can only be challenged via the rare, dangerous Lightbreaker Procedure." },
  { page: "Allruh", url: "allruh.html", heading: "Allruh tasks and ranks", text: "Tasks (Faculties): Guardian (fighters/border security), Keeper (territory/route knowledge), Envoy (diplomacy/cartography), Apothecary (healers), Scholar (historians/teachers). Ranks top-down: The Radiance (alpha), The Zenith, The Smoke, The Apogees (thetas), The Parallaxes (gammas), The Aspects (deltas), The Perigees (omegas), The Starkin (pups), The Drifters (unintegrated newcomers/loners)." },

  // ---- Riverfell (full pack page) ----
  { page: "Riverfell", url: "riverfell.html", heading: "Riverfell overview and history", text: "Riverfell (Matriarchy, Sellswords, Traders, Other Creatures) was founded as a sanctuary for all predators following the golden eagle Siamsa. It shifted from patriarchal to matriarchal rule under the first female alpha, Lady Shiloh, who later exiled herself after violence against packmates; Gold Feather Calumina now leads as alpha." },
  { page: "Riverfell", url: "riverfell.html", heading: "Riverfell culture and customs", text: "Riverfell hosts Quarter Feasts, weddings at the Lake of Stars, and the Heart Stone Passing Ceremony for the dying. Other predators may live in the territory as an independent, protected sanctuary population (not pack members) under a mutual-protection truce. Disputes can be settled with a 'Fight Night' sparring match." },
  { page: "Riverfell", url: "riverfell.html", heading: "Riverfell trade", text: "Riders run Riverfell's trading posts, bartering deer/fish/fruit/herbs for moose, elk, antlers, medicinal herbs, and crystals with loners and other packs." },
  { page: "Riverfell", url: "riverfell.html", heading: "Riverfell tasks and ranks", text: "Tasks: Gold Feathers (elite warriors, hirable), Sages (healers/lore-keepers), Guardians (territory defense), Hunters (rare-prey suppliers), Riders (traders/diplomats/messengers). Ranks top-down: Alpha (Lady/Lord), The Council, Master Sage, Gold Feathers, Seniors (thetas), Captains (gammas), Apprentices (deltas), omegas, juveniles, pups." },

  // ---- Xassa (full pack page) ----
  { page: "Xassa", url: "xassa.html", heading: "Xassa overview and history", text: "Xassa (Peace, Diplomacy, Imperialism, Pursuits, Records) pursues 'Xerxes Peace' — uniting all packs peacefully — but endured a long isolationist era called Hassan's Silence after a diplomatic party was massacred. Cyrus Zagros's dying wish reopened Xassa; his son Nineveh led it, and Nineveh's returned brother Ramman is the current Cyrus." },
  { page: "Xassa", url: "xassa.html", heading: "Xassa religion and culture", text: "Xassa worships the creator god Xerxes (other gods/goddesses are welcome alongside him) and keeps an underground recordkeeping system in the Sacred Caves. The pack is skilled in meteorology and astronomy to predict floods and dangerous weather." },
  { page: "Xassa", url: "xassa.html", heading: "Xassa laws and tasks", text: "Laws include Xerxes' Peace (treat all equally), Retaliation (an eye for an eye), and death for entering the Sacred Caves without a task. Tasks: Magi (priests/cave guardians), Marduk (warriors), Nabu (diplomats), Gula (healers), Su'en (hunters, especially of bison)." },
  { page: "Xassa", url: "xassa.html", heading: "Xassa ranks", text: "Ranks top-down: Cyrus (alpha), The Great Scribe/Melchior, The Council (Darius, Ea, Enlil, Baba), Zarii/Zarr (thetas), Siglosi/Siglos (gammas), Asmani/Asman (deltas), Tulaab/Taleb (omega), pups, Utuian/Utu (guests, forbidden from the Caves on pain of death)." },

  // ---- Grayard (full pack page) ----
  { page: "Grayard", url: "grayard.html", heading: "Grayard overview and history", text: "Grayard (Esoteric, Militaristic, Doomsday, Integrity, Humility) is an old, secretive pack currently led by Honorable Bentwood, who purged and reset the whole pack's ranks after her father's suspected poisoning. Grayardi believe the world will end (\"The Fell\") and strive to die with an honorable, humble ego." },
  { page: "Grayard", url: "grayard.html", heading: "Grayard culture and outsiders", text: "Grayard tests strangers with a coded honesty test called 'the bough.' The pack is militaristic and secretive due to a history of being raided and exploited by neighbors, and is poor at swimming — river bends are named after Grayardi who drowned there, as a deterrent, not a memorial." },
  { page: "Grayard", url: "grayard.html", heading: "Grayard tasks and ranks", text: "Branches (tasks): Gopher (scouts), Watcher (patrol/defense), Rake (engineers/only ones taught to swim), Swift (healers/mediators), Catch (history/ceremonies). Ranks top-down: Alpha/Honorable, Yard Warden, Thew/Alder (Free Council), Rib (thetas), Marrow (gammas), Tendon (deltas), Quick (pledged young), Scab (unpledged outsiders)." },

  // ---- Virtus (full pack page) ----
  { page: "Virtus", url: "virtus.html", heading: "Virtus overview and history", text: "Virtus (Militant, Strength, Fortitude, Pride) is Wolf Club's newest pack, founded by Beatrice — a wolf hardened by loss who gathered deserters, orphans, and rejects into a strict, military-style kindred that values strength and achievement above all." },
  { page: "Virtus", url: "virtus.html", heading: "Virtus initiation and pack life", text: "New/coming-of-age wolves prove themselves via the Rite of Strength, Fortitude, Mind, or the pass/fail Rite of the Champion. Events include the Seasonal Scrimmage and The Great Chase hunting competition. Mates need the Prime's approval; heirship passes to the Prime's children." },
  { page: "Virtus", url: "virtus.html", heading: "Virtus tasks, laws and ranks", text: "Tasks: Warrior (Battalion, border defense), Runner (Squadron, hunters/cartographers), Agent (Consul, diplomats/spies), Mender (Ward, healers), Aide (Administration, assistants/messengers). Punishments escalate from forced labor to imprisonment, mauling, banishment, and death. Ranks top-down: The Prime (alpha), Exarch, The Ring, Vice (betas), Major (thetas), Lieutenant (gammas), Cadet (deltas), Recruits (omegas), Brood (pups)." },

  // ---- Telcoyu (full pack page) ----
  { page: "Telcoyu", url: "telcoyu.html", heading: "Telcoyu overview and history", text: "Telcoyu (Devout, Resilient, Occultism, Hired Killers, Devious) is a secretive swamp-dwelling cult, formerly known as Tél, that worships the Mother and Father and trades assassination-for-hire services (\"Vektren\"). A mysterious she-wolf reshaped the pack after a war with a neighboring pack, leading them to their current holy grounds under a new Soigner." },
  { page: "Telcoyu", url: "telcoyu.html", heading: "Telcoyu religion", text: "Telcoyu worships two gods: the Mother (goddess of darkness) and the Father (god of death), and performs Offering Rituals burying the hearts of eliminated targets in the sacred Reliquary — why outsiders call them a 'Cult' rather than a pack. Atheism is tolerated but non-believers are still bound by the cult's tenets." },
  { page: "Telcoyu", url: "telcoyu.html", heading: "Telcoyu laws and territory", text: "Telcoyu's territory is sacred and forbidden to outsiders, guarded by traps and the Ours; trespassers are killed on sight. Tenets of the Spirit and Flesh forbid dishonoring the gods, betraying the pack's secrets, taking a mate outside Telcoyu, or disobeying a superior. Punishments include labor, reeducation, serfdom, scarification, banishment, and death." },
  { page: "Telcoyu", url: "telcoyu.html", heading: "Telcoyu tasks and ranks", text: "Tasks: Ours (protectors), Fouine (healers/alchemists), Cigale (clerics), Tchoc (hunters/contract killers), Lapin (scouts/traders), Hibou (record-keepers/diplomats). Ranks top-down: Soigner (alpha), Garder, The Council, Fleurir (thetas), Pousser (gammas), Bourgeon (deltas), Semer (omega), Crasse (punished), Dawn (pups), Dusk (elders), Twilight (deceased)." },

  // ---- Contact ----
  { page: "Contact", url: "contact.html", heading: "Contact Wolf Club", text: "The Contact page lists ways to reach Wolf Club: email (contact@wolfclub.com), the group's Discord, a support option, and a 'Send Us a Message' form covering name, email, subject, and message." },
];

// Exported for Node (api/chat.js) via require(), and as a browser global
// (window.WolfClubContentIndex) so the nav search box can search the same
// content client-side without a round trip to /api/chat.
if (typeof module !== "undefined" && module.exports) {
  module.exports = { CONTENT_INDEX };
}
if (typeof window !== "undefined") {
  window.WolfClubContentIndex = { CONTENT_INDEX };
}
